# 
# Makefile for reverse.cu exercise
#

CP= cp

# This is for the course organiser to provide everyone with a copy
# of the templates and the Makefiles in the destination INSTALL_DIR.

install-course-copy:
	$(CP) constant_shared.ipynb $(INSTALL_DIR)
	$(CP) -r src_c              $(INSTALL_DIR)
	$(CP) -r src_fortran        $(INSTALL_DIR)
